package com.bondhu.cockpitdriver

enum class DriverState {
    IDLE, OPENING, DASHBOARD, ENTERING_NUMBER, ENTERING_AMOUNT,
    TAP_POWERLOAD, TAP_NEXT, CONFIRMATION, WAITING_PIN,
    SUBMITTING, SUCCESS, FAILED, STOPPED
}
